"""Tests for the generator modules."""

from job_agent.generator.cover_letter import generate_cover_letter
from job_agent.generator.cv import tailor_cv
from job_agent.generator.qa import answer_screening_questions, MANUAL_REVIEW_MARKER


def test_tailor_cv_returns_markdown(sample_job, sample_master_cv, sample_profile):
    result = tailor_cv(sample_job, sample_master_cv, sample_profile)
    assert isinstance(result, str)
    assert len(result) > 0


def test_tailor_cv_contains_candidate_name(sample_job, sample_master_cv, sample_profile):
    result = tailor_cv(sample_job, sample_master_cv, sample_profile)
    assert "Candidate Data AI Paris" in result


def test_tailor_cv_contains_source_comment(sample_job, sample_master_cv, sample_profile):
    result = tailor_cv(sample_job, sample_master_cv, sample_profile)
    assert "Generated by free-job-agent" in result


def test_tailor_cv_has_experience_section(sample_job, sample_master_cv, sample_profile):
    result = tailor_cv(sample_job, sample_master_cv, sample_profile)
    assert "## Experience" in result


def test_tailor_cv_has_skills_section(sample_job, sample_master_cv, sample_profile):
    result = tailor_cv(sample_job, sample_master_cv, sample_profile)
    assert "## Skills" in result


def test_generate_cover_letter_returns_markdown(sample_job, sample_master_cv, sample_profile):
    result = generate_cover_letter(sample_job, sample_master_cv, sample_profile)
    assert isinstance(result, str)
    assert len(result) > 0


def test_generate_cover_letter_contains_job_title(sample_job, sample_master_cv, sample_profile):
    result = generate_cover_letter(sample_job, sample_master_cv, sample_profile)
    assert sample_job.title in result


def test_generate_cover_letter_contains_company(sample_job, sample_master_cv, sample_profile):
    result = generate_cover_letter(sample_job, sample_master_cv, sample_profile)
    assert sample_job.company in result


def test_generate_cover_letter_contains_source_comment(sample_job, sample_master_cv, sample_profile):
    result = generate_cover_letter(sample_job, sample_master_cv, sample_profile)
    assert "Generated by free-job-agent" in result


def test_answer_screening_questions_matched(sample_qa_profile, sample_profile):
    questions = ["Are you authorized to work in France?"]
    answers = answer_screening_questions(questions, sample_qa_profile, sample_profile)
    assert "Are you authorized to work in France?" in answers
    answer = answers["Are you authorized to work in France?"]
    assert answer != MANUAL_REVIEW_MARKER
    assert "authorized" in answer or "authorized" in answer.lower()


def test_answer_screening_questions_unmatched(sample_qa_profile, sample_profile):
    questions = ["What is your favorite color?"]
    answers = answer_screening_questions(questions, sample_qa_profile, sample_profile)
    assert answers["What is your favorite color?"] == MANUAL_REVIEW_MARKER


def test_answer_screening_questions_mixed(sample_qa_profile, sample_profile):
    questions = [
        "Do you require visa sponsorship?",
        "What is your hobby?",
    ]
    answers = answer_screening_questions(questions, sample_qa_profile, sample_profile)
    assert answers["Do you require visa sponsorship?"] != MANUAL_REVIEW_MARKER
    assert answers["What is your hobby?"] == MANUAL_REVIEW_MARKER


def test_answer_screening_empty_questions(sample_qa_profile, sample_profile):
    answers = answer_screening_questions([], sample_qa_profile, sample_profile)
    assert answers == {}
