"""Cover-letter gating and on-demand generation."""
from __future__ import annotations

from pathlib import Path
import shutil

from job_agent.config import AppConfig
from job_agent.cover_letter_gate import generate_cover_letter_on_demand, should_generate_cover_letter
from job_agent.db import Database
from job_agent.fingerprint import set_fingerprint
from job_agent.pipeline import generate_packet_for_job
from job_agent.schemas.job import JobListing
from job_agent.tracker import ApplicationTracker


EXAMPLES_DIR = Path(__file__).parent.parent / "examples"


def _copy_profiles(tmp_path: Path, *, threshold: int = 70) -> AppConfig:
    data_dir = tmp_path / ".job_agent"
    profiles_dir = data_dir / "profiles"
    outputs_dir = data_dir / "outputs"
    profiles_dir.mkdir(parents=True)
    outputs_dir.mkdir(parents=True)
    for name in ["candidate_profile.json", "master_cv.json", "master_qa_profile.json"]:
        shutil.copyfile(EXAMPLES_DIR / name, profiles_dir / name)
    return AppConfig(
        data_dir=data_dir,
        profiles_dir=profiles_dir,
        outputs_dir=outputs_dir,
        db_path=data_dir / "jobs.db",
        cover_letter_auto_threshold=threshold,
    )


def _save_job(config: AppConfig, job: JobListing) -> JobListing:
    db = Database(config.db_path)
    db.initialize()
    tracker = ApplicationTracker(db)
    job = set_fingerprint(job)
    tracker.add_job(job)
    return job


def test_cover_letter_decision_uses_score_threshold(tmp_path):
    config = AppConfig(data_dir=tmp_path, cover_letter_auto_threshold=70)
    job = JobListing(title="Backend Engineer", company="Example SaaS")

    assert should_generate_cover_letter(job, 70, config) is True
    assert should_generate_cover_letter(job, 69, config) is False


def test_cover_letter_decision_allows_stage_and_alternance_contexts(tmp_path):
    config = AppConfig(data_dir=tmp_path, cover_letter_auto_threshold=101)

    assert should_generate_cover_letter(JobListing(title="Stage Data Scientist", company="ACME"), 20, config) is True
    assert should_generate_cover_letter(JobListing(title="Alternance Data Analyst", company="ACME"), 20, config) is True


def test_low_score_packet_skips_cover_letter_without_calling_generator(tmp_path, monkeypatch):
    config = _copy_profiles(tmp_path, threshold=101)
    job = _save_job(
        config,
        JobListing(
            title="Backend Engineer",
            company="Example SaaS",
            description="Build internal tooling.",
            requirements=["Go"],
            tech_stack=["go"],
        ),
    )

    def _explode(*args, **kwargs):
        raise AssertionError("cover letter generator should not run")

    monkeypatch.setattr("job_agent.pipeline.generate_cover_letter", _explode)
    packet = generate_packet_for_job(config, job.id)

    names = {Path(artifact.path).name for artifact in packet.artifacts}
    assert "cover_letter.md" not in names
    assert "cover_letter.pdf" not in names
    assert packet.cover_letter_md == ""
    assert packet.cover_letter_pdf_path == ""


def test_on_demand_cover_letter_persists_to_latest_packet(tmp_path):
    config = _copy_profiles(tmp_path, threshold=101)
    job = _save_job(
        config,
        JobListing(
            title="Backend Engineer",
            company="Example SaaS",
            description="Build internal tooling.",
            requirements=["Go"],
            tech_stack=["go"],
        ),
    )
    packet = generate_packet_for_job(config, job.id)
    assert packet.cover_letter_pdf_path == ""

    updated = generate_cover_letter_on_demand(config, job.id)

    names = {Path(artifact.path).name for artifact in updated.artifacts}
    assert "cover_letter.md" in names
    assert "cover_letter.html" in names
    assert "cover_letter.pdf" in names
    assert Path(updated.cover_letter_pdf_path or "").exists()
    assert updated.cover_letter_md.startswith("<!-- Generated by free-job-agent")
