"""Generate a fact-grounded cover letter as Markdown."""
from __future__ import annotations

import re

from job_agent.generator.company_extract import resolve_company_for_letter
from job_agent.generator.cv import _score_experience, _rank_bullets
from job_agent.renderer.latex_render import _clean_role_phrase, _detect_contract_family
from job_agent.schemas.candidate import CandidateProfile, MasterCV
from job_agent.schemas.job import JobListing

try:
    from job_agent.ai_agent import draft_cover_letter_body as _ai_draft_body
except Exception:  # pragma: no cover - AI is optional
    def _ai_draft_body(*args, **kwargs):  # type: ignore[misc]
        return []


# The master CV often mentions "6-month internship" — fine when the job is a
# stage, wrong when the job is an alternance or a permanent role. We rewrite
# those phrases in the cover-letter summary on the fly when the contract is
# something else.
_INTERNSHIP_SENTENCE_RE = re.compile(
    r"(?:[^.!?]*?\b(?:internship|stage|end[- ]of[- ]studies|6[- ]?month|six[- ]?month)\b[^.!?]*?[.!?])",
    re.IGNORECASE,
)


def _adjust_summary_for_contract(summary: str, job: JobListing) -> str:
    """Drop or rewrite internship-only phrasing when the job isn't a stage."""
    if not summary:
        return summary
    contract = _detect_contract_family(job)
    if contract == "stage":
        return summary
    role_phrase = _clean_role_phrase(job.title or "") or "Data Science"
    if contract == "alternance":
        replacement_en = (
            f"Seeking an alternance in {role_phrase} to apply machine learning, deep learning, and data engineering skills."
        )
    elif contract == "cdi":
        replacement_en = (
            f"Open to permanent {role_phrase} opportunities where I can apply my data science, ML, and software engineering background."
        )
    else:
        replacement_en = (
            f"Applying for {role_phrase} roles to combine data science, ML, and software engineering skills."
        )
    rewritten, replacements = _INTERNSHIP_SENTENCE_RE.subn(replacement_en, summary, count=1)
    if not replacements:
        # Master summary didn't contain a stage-specific sentence — append a
        # contract-aware closer instead so we don't say "internship" in an
        # alternance cover letter.
        rewritten = summary.rstrip(".") + ". " + replacement_en
    return rewritten


def generate_cover_letter(job: JobListing, master_cv: MasterCV, profile: CandidateProfile) -> str:
    """Generate a concise cover letter using only profile/master CV facts.

    When a local AI model is available, the body paragraphs come from the AI
    drafter (which only uses facts from the candidate + job, validated via
    vocabulary overlap). Otherwise a deterministic template is used. Either
    way, sponsorship/visa claims are never invented.

    The greeting / header always uses the *real* company extracted from the
    job description when the aggregator (e.g. France Travail) reports itself
    as the company. Wording is also contract-aware so an alternance posting
    doesn't get an "internship" letter.
    """
    real_company = resolve_company_for_letter(job)
    lines: list[str] = []
    lines.append("<!-- Generated by free-job-agent. All facts sourced from profile/master_cv. -->")
    lines.append("")
    c = master_cv.contact
    role_display = _clean_role_phrase(job.title or "") or job.title
    company_known = real_company.strip().casefold() != "the hiring team"
    target_phrase = f"at {real_company}" if company_known else "for this hiring team"
    lines.append(f"# Cover Letter — {role_display} {target_phrase}")
    lines.append("")
    lines.append(f"**{c.name}**  ")
    lines.append(f"{c.email}  ")
    if c.phone:
        lines.append(f"{c.phone}  ")
    lines.append("")
    lines.append(f"Dear Hiring Manager at {real_company}," if company_known else "Dear Hiring Team,")
    lines.append("")
    ai_paragraphs = _ai_draft_body(job, master_cv, profile)
    if ai_paragraphs:
        for paragraph in ai_paragraphs:
            lines.append(paragraph)
            lines.append("")
    else:
        summary = master_cv.summary or profile.summary
        summary = _adjust_summary_for_contract(summary, job)
        lines.append(
            f"I am writing to apply for the **{role_display}** role {target_phrase}. "
            f"{summary}"
        )
        lines.append("")
        scored = sorted(master_cv.experience, key=lambda e: _score_experience(e, job), reverse=True)
        examples: list[str] = []
        for exp in scored[:2]:
            bullets = _rank_bullets(exp.bullet_points, job, 1)
            if bullets:
                examples.append(
                    f"One relevant example from my work as **{exp.title}** at **{exp.company}** is: {bullets[0]}"
                )
        if examples:
            lines.append(" ".join(examples))
            lines.append("")
        if job.tech_stack:
            lines.append(
                f"The role's focus on **{', '.join(job.tech_stack[:5])}** aligns with the experience and projects highlighted in my CV."
            )
            lines.append("")
    closing = (
        f"I would welcome the opportunity to discuss how my background can contribute to {real_company}'s team. "
        if company_known
        else "I would welcome the opportunity to discuss how my background can contribute to your team. "
    )
    lines.append(closing + "Thank you for considering my application.")
    lines.append("")
    lines.append("Sincerely,  ")
    lines.append(f"**{c.name}**")
    lines.append("")
    return "\n".join(lines)
