"""Generate a fact-grounded cover letter as Markdown."""
from __future__ import annotations

from job_agent.schemas.candidate import CandidateProfile, MasterCV
from job_agent.schemas.job import JobListing
from job_agent.generator.cv import _score_experience, _rank_bullets

try:
    from job_agent.ai_agent import draft_cover_letter_body as _ai_draft_body
except Exception:  # pragma: no cover - AI is optional
    def _ai_draft_body(*args, **kwargs):  # type: ignore[misc]
        return []


def generate_cover_letter(job: JobListing, master_cv: MasterCV, profile: CandidateProfile) -> str:
    """Generate a concise cover letter using only profile/master CV facts.

    When a local AI model is available, the body paragraphs come from the AI
    drafter (which only uses facts from the candidate + job, validated via
    vocabulary overlap). Otherwise a deterministic template is used. Either
    way, sponsorship/visa claims are never invented.
    """
    lines: list[str] = []
    lines.append("<!-- Generated by free-job-agent. All facts sourced from profile/master_cv. -->")
    lines.append("")
    c = master_cv.contact
    lines.append(f"# Cover Letter — {job.title} at {job.company}")
    lines.append("")
    lines.append(f"**{c.name}**  ")
    lines.append(f"{c.email}  ")
    if c.phone:
        lines.append(f"{c.phone}  ")
    lines.append("")
    lines.append(f"Dear Hiring Manager at {job.company},")
    lines.append("")
    ai_paragraphs = _ai_draft_body(job, master_cv, profile)
    if ai_paragraphs:
        for paragraph in ai_paragraphs:
            lines.append(paragraph)
            lines.append("")
    else:
        summary = master_cv.summary or profile.summary
        lines.append(
            f"I am writing to apply for the **{job.title}** role at **{job.company}**. "
            f"{summary}"
        )
        lines.append("")
        scored = sorted(master_cv.experience, key=lambda e: _score_experience(e, job), reverse=True)
        examples: list[str] = []
        for exp in scored[:2]:
            bullets = _rank_bullets(exp.bullet_points, job, 1)
            if bullets:
                examples.append(
                    f"One relevant example from my work as **{exp.title}** at **{exp.company}** is: {bullets[0]}"
                )
        if examples:
            lines.append(" ".join(examples))
            lines.append("")
        if job.tech_stack:
            lines.append(
                f"The role's focus on **{', '.join(job.tech_stack[:5])}** aligns with the experience and projects highlighted in my CV."
            )
            lines.append("")
    lines.append(
        f"I would welcome the opportunity to discuss how my background can contribute to {job.company}'s team. "
        "Thank you for considering my application."
    )
    lines.append("")
    lines.append("Sincerely,  ")
    lines.append(f"**{c.name}**")
    lines.append("")
    return "\n".join(lines)
