"""Tailor a CV as Markdown to a specific job listing."""
from __future__ import annotations

from job_agent.polish import PolishOptions, polish_bullets
from job_agent.schemas.candidate import CandidateProfile, MasterCV, WorkExperience, Project
from job_agent.schemas.job import JobListing
from job_agent.utils import fuzzy


def _keyword_score(text: str, keywords: list[str]) -> int:
    if not keywords:
        return 50
    text_lower = text.lower()
    score = 0
    for kw in keywords:
        kw_lower = kw.lower()
        if kw_lower in text_lower:
            score += 3
        elif fuzzy.partial_ratio(kw_lower, text_lower) >= 85:
            score += 1
    return score


def _score_experience(exp: WorkExperience, job: JobListing) -> int:
    keywords = job.tech_stack + job.requirements + [job.title]
    tech_text = " ".join(exp.technologies)
    bullet_text = " ".join(exp.bullet_points)
    return _keyword_score(tech_text + " " + bullet_text, keywords)


def _rank_bullets(bullets: list[str], job: JobListing, limit: int) -> list[str]:
    keywords = job.tech_stack + job.requirements + job.responsibilities + [job.title]
    scored = sorted(((b, _keyword_score(b, keywords)) for b in bullets), key=lambda x: x[1], reverse=True)
    selected = [b for b, _ in scored[:limit]]
    return selected or bullets[:limit]


def _score_project(project: Project, job: JobListing) -> int:
    keywords = job.tech_stack + job.requirements + [job.title]
    text = f"{project.name} {project.description} {' '.join(project.technologies)} {' '.join(project.bullet_points)}"
    return _keyword_score(text, keywords)


def tailor_cv(job: JobListing, master_cv: MasterCV, profile: CandidateProfile) -> str:
    """Generate a tailored CV in Markdown.

    The function reorders and selects existing facts only. It does not invent
    experience, metrics, education, work authorization, or certifications.
    """
    lines: list[str] = []
    lines.append("<!-- Generated by free-job-agent. All facts sourced from master_cv.json/profile. -->")
    lines.append("")

    c = master_cv.contact
    lines.append(f"# {c.name}")
    contact_parts = [p for p in [c.email, c.phone, c.location] if p]
    if c.linkedin_url:
        contact_parts.append(c.linkedin_url)
    if c.github_url:
        contact_parts.append(c.github_url)
    if c.portfolio_url:
        contact_parts.append(c.portfolio_url)
    lines.append(" | ".join(contact_parts))
    lines.append("")

    if master_cv.summary:
        lines.append("## Summary")
        lines.append("")
        lines.append(master_cv.summary)
        lines.append("")

    if master_cv.skills:
        lines.append("## Skills")
        lines.append("")
        job_text = " ".join(job.tech_stack + job.requirements + job.responsibilities).lower()
        relevant = [
            s for s in master_cv.skills
            if not job.tech_stack
            or s.name.lower() in job_text
            or any(fuzzy.ratio(s.name.lower(), jt.lower()) >= 82 for jt in job.tech_stack)
        ]
        if not relevant:
            relevant = master_cv.skills
        by_cat: dict[str, list[str]] = {}
        for s in relevant:
            by_cat.setdefault(s.category or "general", []).append(s.name)
        for cat, names in sorted(by_cat.items()):
            lines.append(f"**{cat.title()}:** {', '.join(sorted(set(names), key=str.lower))}")
        lines.append("")

    polish_opts = PolishOptions.from_env()
    if master_cv.experience:
        lines.append("## Experience")
        lines.append("")
        scored_exps = sorted(master_cv.experience, key=lambda e: _score_experience(e, job), reverse=True)
        for exp in scored_exps:
            end = exp.end_date or "Present"
            loc = f" | {exp.location}" if exp.location else ""
            lines.append(f"### {exp.title} — {exp.company}{loc}")
            lines.append(f"*{exp.start_date} – {end}*")
            lines.append("")
            max_bullets = getattr(master_cv, "max_experience_bullets_per_role", 4) or 4
            bullets = _rank_bullets(exp.bullet_points, job, max_bullets)
            for bp in polish_bullets(bullets, polish_opts):
                lines.append(f"- {bp}")
            if exp.technologies:
                lines.append(f"**Technologies:** {', '.join(exp.technologies)}")
            lines.append("")

    if master_cv.projects:
        lines.append("## Projects")
        lines.append("")
        max_projects = getattr(master_cv, "max_projects", 3) or 3
        for proj in sorted(master_cv.projects, key=lambda p: _score_project(p, job), reverse=True)[:max_projects]:
            url_part = f" ([link]({proj.url}))" if proj.url else ""
            lines.append(f"### {proj.name}{url_part}")
            lines.append(proj.description)
            for bp in polish_bullets(_rank_bullets(proj.bullet_points, job, 2), polish_opts):
                lines.append(f"- {bp}")
            if proj.technologies:
                lines.append(f"**Technologies:** {', '.join(proj.technologies)}")
            lines.append("")

    if master_cv.education:
        lines.append("## Education")
        lines.append("")
        for edu in master_cv.education:
            years = ""
            if edu.start_year or edu.end_year:
                years = f"*{edu.start_year or ''} – {edu.end_year or 'Present'}*"
            field = f" in {edu.field}" if edu.field else ""
            lines.append(f"### {edu.degree}{field} — {edu.institution}")
            if years:
                lines.append(years)
            if edu.honors:
                lines.append(f"Honors: {', '.join(edu.honors)}")
            if edu.notes:
                for note in edu.notes:
                    lines.append(f"- {note}")
            lines.append("")

    if master_cv.certifications:
        lines.append("## Certifications")
        lines.append("")
        for cert in master_cv.certifications:
            year = f" ({cert.year})" if cert.year else ""
            url_part = f" ([link]({cert.url}))" if cert.url else ""
            lines.append(f"- {cert.name} — {cert.issuer}{year}{url_part}")
        lines.append("")

    return "\n".join(lines)
