"""Tailor a CV (as Markdown) to a specific job listing."""
from __future__ import annotations

from rapidfuzz import fuzz

from job_agent.schemas.candidate import CandidateProfile, MasterCV
from job_agent.schemas.job import JobListing


def _score_experience(exp_technologies: list[str], job_tech: list[str]) -> float:
    """Score relevance of a work experience to the job tech stack."""
    if not job_tech:
        return 0.5
    exp_lower = [t.lower() for t in exp_technologies]
    job_lower = [t.lower() for t in job_tech]
    matched = sum(
        1
        for jt in job_lower
        for et in exp_lower
        if fuzz.ratio(jt, et) >= 80
    )
    return matched / len(job_lower)


def tailor_cv(job: JobListing, master_cv: MasterCV, profile: CandidateProfile) -> str:
    """Generate a tailored CV in Markdown. Only uses facts from master_cv."""
    lines: list[str] = []
    lines.append("<!-- Generated by free-job-agent. All facts sourced from master_cv.json -->")
    lines.append("")

    # Header
    c = master_cv.contact
    lines.append(f"# {c.name}")
    contact_parts = [p for p in [c.email, c.phone, c.location] if p]
    if c.linkedin_url:
        contact_parts.append(c.linkedin_url)
    if c.github_url:
        contact_parts.append(c.github_url)
    lines.append(" | ".join(contact_parts))
    lines.append("")

    # Summary
    if master_cv.summary:
        lines.append("## Summary")
        lines.append("")
        lines.append(master_cv.summary)
        lines.append("")

    # Experience — sorted by relevance to job
    if master_cv.experience:
        lines.append("## Experience")
        lines.append("")
        scored = sorted(
            master_cv.experience,
            key=lambda e: _score_experience(e.technologies, job.tech_stack),
            reverse=True,
        )
        for exp in scored:
            end = exp.end_date or "Present"
            loc = f" | {exp.location}" if exp.location else ""
            lines.append(f"### {exp.title} — {exp.company}{loc}")
            lines.append(f"*{exp.start_date} – {end}*")
            lines.append("")
            for bp in exp.bullet_points:
                lines.append(f"- {bp}")
            if exp.technologies:
                lines.append(f"**Technologies:** {', '.join(exp.technologies)}")
            lines.append("")

    # Skills — filter to those relevant to the job
    if master_cv.skills:
        lines.append("## Skills")
        lines.append("")
        job_text = " ".join(job.tech_stack + job.requirements).lower()
        relevant = [
            s for s in master_cv.skills
            if not job.tech_stack or s.name.lower() in job_text
            or any(fuzz.ratio(s.name.lower(), jt.lower()) >= 80 for jt in job.tech_stack)
        ]
        if not relevant:
            relevant = master_cv.skills
        by_cat: dict[str, list[str]] = {}
        for s in relevant:
            by_cat.setdefault(s.category, []).append(s.name)
        for cat, names in by_cat.items():
            lines.append(f"**{cat.title()}:** {', '.join(names)}")
        lines.append("")

    # Education
    if master_cv.education:
        lines.append("## Education")
        lines.append("")
        for edu in master_cv.education:
            end = str(edu.end_year) if edu.end_year else "Present"
            lines.append(f"### {edu.degree} in {edu.field} — {edu.institution}")
            lines.append(f"*{edu.start_year} – {end}*")
            if edu.honors:
                lines.append(f"Honors: {', '.join(edu.honors)}")
            lines.append("")

    # Projects
    if master_cv.projects:
        lines.append("## Projects")
        lines.append("")
        for proj in master_cv.projects:
            url_part = f" ([link]({proj.url}))" if proj.url else ""
            lines.append(f"### {proj.name}{url_part}")
            lines.append(proj.description)
            if proj.technologies:
                lines.append(f"**Technologies:** {', '.join(proj.technologies)}")
            lines.append("")

    # Certifications
    if master_cv.certifications:
        lines.append("## Certifications")
        lines.append("")
        for cert in master_cv.certifications:
            url_part = f" ([link]({cert.url}))" if cert.url else ""
            lines.append(f"- {cert.name} — {cert.issuer} ({cert.year}){url_part}")
        lines.append("")

    return "\n".join(lines)
