"""Export the local job database into a linked Obsidian vault.

The point of the vault is the *graph*: each job note wikilinks to its company
and skills, so Obsidian surfaces companies and skills as hub nodes and the graph
becomes a real map of the search (which companies you're chasing, which skills
recur, what's NEEDS_MANUAL vs PACKET_READY). A generated ``Dashboard.md`` MOC
gives a navigable entry point.

All output stays local (the vault is gitignored); only this generator ships.
"""
from __future__ import annotations

import logging
import re
from collections import defaultdict
from pathlib import Path
from typing import Any, Iterable

from job_agent.schemas.job import JobListing

logger = logging.getLogger(__name__)

_SLUG_RE = re.compile(r"[^a-z0-9]+")
_MAX_BODY_CHARS = 1200


def _slugify(text: str) -> str:
    slug = _SLUG_RE.sub("-", (text or "").lower()).strip("-")
    return slug or "untitled"


def _job_slug(job: JobListing) -> str:
    return f"{_slugify(job.title)}-{_slugify(job.company)}"


def _skills(job: JobListing) -> list[str]:
    # tech_stack is the richest skill signal; de-dupe case-insensitively.
    seen: dict[str, str] = {}
    for raw in job.tech_stack or []:
        slug = _slugify(raw)
        seen.setdefault(slug, raw)
    return list(seen)  # slugs


def _yaml_list(items: Iterable[str]) -> str:
    return "[" + ", ".join(items) + "]"


def _job_note(job: JobListing) -> str:
    company_slug = _slugify(job.company)
    skill_slugs = _skills(job)
    tags = ["job", *skill_slugs]
    score = "" if job.fit_score is None else str(int(round(job.fit_score)))
    apply_url = job.apply_url or job.source_url or ""
    front = [
        "---",
        f'title: "{job.title}"',
        f'company: "[[{company_slug}|{job.company}]]"',
        f"status: {job.status.value}",
        *([f"score: {score}"] if score else []),
        *([f'location: "{job.location}"'] if job.location else []),
        f"remote: {str(job.remote).lower()}",
        f"source: {job.source}",
        *([f'apply_url: "{apply_url}"'] if apply_url else []),
        f"tags: {_yaml_list(tags)}",
        f"updated: {job.updated_at}",
        "---",
        "",
    ]
    skill_links = " · ".join(f"[[{s}]]" for s in skill_slugs) or "_none recorded_"
    loc = job.location or "—"
    if job.remote:
        loc += " (remote)"
    body = [
        f"# {job.title} — {job.company}",
        "",
        f"**Company:** [[{company_slug}|{job.company}]]",
        f"**Status:** {job.status.value}" + (f" · **Fit:** {score}/100" if score else ""),
        f"**Location:** {loc}",
        *([f"**Apply:** {apply_url}"] if apply_url else []),
        "",
        "## Skills",
        skill_links,
        "",
        "## Notes",
        (job.raw_text or job.description or "").strip()[:_MAX_BODY_CHARS] or "_No description captured._",
        "",
    ]
    return "\n".join(front + body)


def _hub_note(name: str, kind: str, lines: list[str]) -> str:
    return "\n".join(
        ["---", f"tags: [{kind}]", "---", "", f"# {name}", "", *lines, ""]
    )


def _dashboard(jobs: list[JobListing]) -> str:
    by_status: dict[str, list[JobListing]] = defaultdict(list)
    for job in jobs:
        by_status[job.status.value].append(job)
    lines = [
        "# Job Search Dashboard",
        "",
        f"_Generated by `job-agent obsidian-sync` — {len(jobs)} job(s)._",
        "",
        "## By status",
    ]
    for status in sorted(by_status):
        group = by_status[status]
        lines.append(f"### {status} ({len(group)})")
        for job in sorted(group, key=lambda j: (j.fit_score or 0), reverse=True):
            slug = _job_slug(job)
            score = "" if job.fit_score is None else f" — {int(round(job.fit_score))}"
            lines.append(f"- [[jobs/{slug}|{job.title} @ {job.company}]]{score}")
        lines.append("")
    top = sorted((j for j in jobs if j.fit_score is not None),
                 key=lambda j: j.fit_score or 0, reverse=True)[:10]
    if top:
        lines.append("## Top fits")
        for job in top:
            lines.append(
                f"- [[jobs/{_job_slug(job)}|{job.title} @ {job.company}]] "
                f"— {int(round(job.fit_score or 0))}"
            )
        lines.append("")
    # Optional Dataview view (renders only if the Dataview plugin is installed).
    lines += [
        "## All jobs (Dataview)",
        "```dataview",
        "table status, score, location from \"jobs\" sort score desc",
        "```",
        "",
    ]
    return "\n".join(lines)


def _resolve_vault(config: Any, vault_path: Path | str | None) -> Path:
    if vault_path is not None:
        return Path(vault_path)
    configured = getattr(config, "obsidian_vault_dir", None)
    return Path(configured) if configured else Path.cwd() / "second-brain"


def _load_jobs(config: Any) -> list[JobListing]:
    from job_agent.db.database import Database
    from job_agent.tracker import ApplicationTracker

    config.ensure_dirs()
    tracker = ApplicationTracker(Database(config.db_path))
    return list(tracker.list_jobs(limit=None))


def export_obsidian_vault(
    config: Any,
    *,
    vault_path: Path | str | None = None,
    jobs: list[JobListing] | None = None,
) -> tuple[Path, int]:
    """Write ``jobs`` (or the DB's jobs) into a linked Obsidian vault.

    Returns ``(vault_path, job_count)``. Creates ``jobs/``, ``companies/`` and
    ``skills/`` note folders plus a ``Dashboard.md`` map-of-content. Re-running
    overwrites the generated notes in place (stable, slug-based filenames).
    """
    vault = _resolve_vault(config, vault_path)
    if jobs is None:
        jobs = _load_jobs(config)

    jobs_dir = vault / "jobs"
    companies_dir = vault / "companies"
    skills_dir = vault / "skills"
    for folder in (jobs_dir, companies_dir, skills_dir):
        folder.mkdir(parents=True, exist_ok=True)

    by_company: dict[str, list[JobListing]] = defaultdict(list)
    by_skill: dict[str, list[JobListing]] = defaultdict(list)

    for job in jobs:
        (jobs_dir / f"{_job_slug(job)}.md").write_text(_job_note(job), encoding="utf-8")
        by_company[job.company].append(job)
        for skill in _skills(job):
            by_skill[skill].append(job)

    for company, group in by_company.items():
        links = [
            f"- [[jobs/{_job_slug(j)}|{j.title}]] — {j.status.value}"
            + ("" if j.fit_score is None else f" ({int(round(j.fit_score))})")
            for j in group
        ]
        (companies_dir / f"{_slugify(company)}.md").write_text(
            _hub_note(company, "company", ["## Jobs", *links]), encoding="utf-8"
        )

    for skill_slug, group in by_skill.items():
        links = [f"- [[jobs/{_job_slug(j)}|{j.title} @ {j.company}]]" for j in group]
        (skills_dir / f"{skill_slug}.md").write_text(
            _hub_note(skill_slug, "skill", ["## Appears in", *links]), encoding="utf-8"
        )

    (vault / "Dashboard.md").write_text(_dashboard(jobs), encoding="utf-8")
    logger.info("Obsidian vault exported: %d jobs -> %s", len(jobs), vault)
    return vault, len(jobs)
